wandb_version: 1

wandb:
  desc: null
  value: true
use_box:
  desc: null
  value: false
log_interval:
  desc: null
  value: 1
num_epochs:
  desc: null
  value: 100
img_size:
  desc: null
  value: 224
patch_size:
  desc: null
  value: 14
num_workers:
  desc: null
  value: 8
batch_size:
  desc: null
  value: 64
dataset:
  desc: null
  value:
    img_dir: /mnt/data/CUB_200_2011/images/
    box_file: /mnt/data/CUB_200_2011/bounding_boxes.txt
    label_file: /mnt/data/CUB_200_2011/image_class_labels.txt
    img_file: /mnt/data/CUB_200_2011/images.txt
model:
  desc: null
  value:
    type: dinov2_vits14
    MLP_dim: 500
    n_classes: 200
opt:
  desc: null
  value:
    type: adamW
    lr: 0.01
_wandb:
  desc: null
  value:
    python_version: 3.10.7
    cli_version: 0.15.7
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: true
    start_time: 1690905290.870778
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 16
      - 23
      4: 3.10.7
      5: 0.15.7
      8:
      - 2
      - 5
